### ISSUE TITLE
Обращение к БД

### ISSUE THREAD

**Issue by AlexanderPlatinum** [YuriyNasretdinov/distribkv#1]
https://github.com/YuriyNasretdinov/distribkv/blob/90d64a7b0aa08be3d67a730a46e210abd9a3ecfd/web/web.go#L47

Сначала происходит обращение к БД, потом идет проверка шарда и редирект.
По этому предлагаю перенести выборку из базы данных после редиректа.

**Comment by YuriyNasretdinov** [comment]
Yeah, thanks for catching that the lookup is performed before the redirect! Would you like to send a pull request so that I can mention you as a comrade contributor in the video? Thanks

**Comment by YuriyNasretdinov** [comment]
Thank you for your contribution!
